from datetime import datetime

from sqlalchemy import BigInteger, DateTime, Identity, func
from sqlalchemy.orm import Mapped, mapped_column


class IdMixin:
    """Adds a ``BIGINT`` surrogate primary key generated by PostgreSQL.

    Uses ``GENERATED BY DEFAULT AS IDENTITY`` (``Identity(always=False)``),
    the modern Postgres replacement for ``SERIAL``. ``BIGINT`` avoids the
    ~2.1B-row ceiling of ``INTEGER`` at negligible cost.
    """

    id: Mapped[int] = mapped_column(
        BigInteger,
        Identity(always=False),
        primary_key=True,
    )


class TimestampMixin:
    """Adds timezone-aware ``created_at`` / ``updated_at`` columns.

    Timestamps are generated by PostgreSQL (``func.now()`` -> ``now()``),
    not by Python, so every row is stamped by a single authoritative clock
    regardless of which application instance issues the write.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
